---
# 1. VERIFICAÇÃO E DOWNLOAD
- name: Verificar se o Hadoop já está instalado
  stat:
    path: "{{ install_dir }}/hadoop-{{ hadoop_version }}"
  register: hadoop_installed

- name: Baixar binários do Apache Hadoop
  get_url:
    url: "{{ hadoop_mirror }}"
    dest: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"
    timeout: 300
  when: not hadoop_installed.stat.exists

- name: Descompactar Hadoop
  unarchive:
    src: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "{{ install_dir }}"
    remote_src: yes
  when: not hadoop_installed.stat.exists

# 2. PERMISSÕES
- name: Criar link simbólico para o Hadoop
  file:
    src: "{{ install_dir }}/hadoop-{{ hadoop_version }}"
    dest: "{{ install_dir }}/hadoop"
    state: link

- name: Ajustar dono da pasta do Hadoop para o usuário vagrant
  file:
    path: "{{ install_dir }}/hadoop-{{ hadoop_version }}"
    owner: vagrant
    group: vagrant
    recurse: yes

# 3. CONFIGURAÇÃO DE AMBIENTE
- name: Fixar JAVA_HOME no hadoop-env.sh (Início do arquivo)
  lineinfile:
    path: "{{ install_dir }}/hadoop/etc/hadoop/hadoop-env.sh"
    insertbefore: BOF
    line: "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"

- name: Configurar templates do Hadoop
  template:
    src: "{{ item }}.j2"
    dest: "{{ install_dir }}/hadoop/etc/hadoop/{{ item }}"
  loop:
    - core-site.xml
    - hdfs-site.xml

# 4. DIRETÓRIOS E FORMATAÇÃO
- name: Criar diretórios de dados
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'
  loop:
    - /opt/hadoop/data/namenode
    - /opt/hadoop/data/datanode

# COMENTE OU DELETE ESTA TAREFA:
#- name: Limpar dados antigos para evitar conflitos
#  file:
#    path: "/opt/hadoop/data/namenode/current"
#    state: absent

- name: Formatar NameNode
  shell: |
    export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    export HADOOP_HOME={{ install_dir }}/hadoop
    export LD_LIBRARY_PATH=$JAVA_HOME/lib/server:$LD_LIBRARY_PATH
    $HADOOP_HOME/bin/hdfs namenode -format -nonInteractive
  args:
    # O Ansible só roda esse comando se este arquivo/pasta NÃO existir
    creates: "/opt/hadoop/data/namenode/current"
  become_user: vagrant

# 5. INICIALIZAÇÃO
- name: Iniciar serviços do HDFS
  shell: |
    export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    export HADOOP_HOME={{ install_dir }}/hadoop
    export LD_LIBRARY_PATH=$JAVA_HOME/lib/server:$LD_LIBRARY_PATH
    export PATH=$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$JAVA_HOME/bin:$PATH
    
    $HADOOP_HOME/sbin/start-dfs.sh
  args:
    # O Ansible só executará o shell acima se este arquivo NÃO existir.
    # Se o arquivo existir, ele pula a tarefa e retorna "OK" (verde).
    creates: "/tmp/hadoop-vagrant-namenode.pid"
  become_user: vagrant