---
- name: Verificar se o Hadoop já está instalado
  stat:
    path: "{{ install_dir }}/hadoop-{{ hadoop_version }}"
  register: hadoop_installed

- name: Baixar binários do Apache Hadoop
  get_url:
    url: "{{ hadoop_mirror }}"
    dest: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"
    timeout: 300
  when: not hadoop_installed.stat.exists

- name: Descompactar Hadoop
  unarchive:
    src: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "{{ install_dir }}"
    remote_src: yes
  when: not hadoop_installed.stat.exists

- name: Criar link simbólico para o Hadoop
  file:
    src: "{{ install_dir }}/hadoop-{{ hadoop_version }}"
    dest: "{{ install_dir }}/hadoop"
    state: link

- name: Descobrir o caminho real do JAVA_HOME
  shell: "readlink -f /usr/bin/java | sed 's:/bin/java::'"
  register: java_path_cmd
  changed_when: false

- name: Definir variável java_home
  set_fact:
    real_java_home: "{{ java_path_cmd.stdout }}"

- name: Configurar JAVA_HOME dentro do hadoop-env.sh
  lineinfile:
    path: "{{ install_dir }}/hadoop/etc/hadoop/hadoop-env.sh"
    regexp: '^# export JAVA_HOME='
    line: "export JAVA_HOME={{ real_java_home }}"

- name: Configurar templates do Hadoop (core-site e hdfs-site)
  template:
    src: "{{ item }}.j2"
    dest: "{{ install_dir }}/hadoop/etc/hadoop/{{ item }}"
  loop:
    - core-site.xml
    - hdfs-site.xml

- name: Adicionar Hadoop ao PATH no .bashrc
  blockinfile:
    path: /home/vagrant/.bashrc
    block: |
      export HADOOP_HOME={{ install_dir }}/hadoop
      export JAVA_HOME={{ real_java_home }}
      export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

- name: Criar diretórios de dados do Hadoop
  file:
    path: "{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'
    recurse: yes
  loop:
    - /opt/hadoop/data/namenode
    - /opt/hadoop/data/datanode

- name: Formatar NameNode (apenas se não houver dados)
  shell: "{{ install_dir }}/hadoop/bin/hdfs namenode -format -nonInteractive"
  args:
    creates: "/opt/hadoop/data/namenode/current"
  environment:
    JAVA_HOME: "{{ real_java_home }}"
    HADOOP_HOME: "{{ install_dir }}/hadoop"
  become_user: vagrant

- name: Iniciar serviços do HDFS
  shell: "{{ install_dir }}/hadoop/sbin/start-dfs.sh"
  become_user: vagrant
  environment:
    JAVA_HOME: "{{ real_java_home }}"
    HADOOP_HOME: "{{ install_dir }}/hadoop"