---
trino_version: "442" # Versão estável (requer Java 17 ou 21)

# Instalação via url tornou-se muito lenta, optei por manter o arquivo na pasta files 
# trino_mirror: "https://repo1.maven.org/maven2/io/trino/trino-server/{{ trino_version }}/trino-server-{{ trino_version }}.tar.gz"

install_dir: "/opt"
data_dir: "/opt/trino/var"