---
- name: Atualizar cache do apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar dependências essenciais (Java, Python, Utils)
  apt:
    name:
      - openjdk-11-jre-headless  # Força as bases da VM
      - openjdk-11-jdk           # JDK completo para o Hadoop
      - python3
      - python-is-python3
      - curl
      - wget
      - rsync
      - unzip
    state: present

- name: Garantir que o grupo vagrant existe
  group:
    name: vagrant
    state: present

- name: Garantir que o usuário vagrant está no grupo
  user:
    name: vagrant
    groups: vagrant
    append: yes