[hadoop_nodes]
hadoop-node ansible_host=192.168.56.10 ansible_ssh_private_key_file=/home/ericson/.ssh/hadoop_vagrant_key

[trino_nodes]
trino-node ansible_host=192.168.56.11 ansible_ssh_private_key_file=/home/ericson/.ssh/trino_vagrant_key

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'