[hadoop_nodes]
hadoop-node ansible_host=192.168.56.10 ansible_ssh_private_key_file=/home/ericson/.ssh/bigdata_lab/hadoop_key

[trino_nodes]
trino-node ansible_host=192.168.56.11 ansible_ssh_private_key_file=/home/ericson/.ssh/bigdata_lab/trino_key

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'